#pragma once

#include "HyperionDef.h"

IGNORE_PADDING_START
IGNORE_SIGNED_BITFIELD_START
IGNORE_UNKNOWN_DOC_COMMAND_START
IGNORE_WEAK_VTABLES_START
IGNORE_CONSTRUCTOR_SHADOW_FIELDS_START
IGNORE_COMMA_MISUSE_START
IGNORE_RESERVED_IDENTIFIERS_START
IGNORE_MISSING_NORETURN_START

#include <fmt/chrono.h>
#include <fmt/color.h>
#include <fmt/compile.h>
#include <fmt/format.h>
#include <fmt/os.h>

IGNORE_MISSING_NORETURN_STOP
IGNORE_RESERVED_IDENTIFIERS_STOP
IGNORE_COMMA_MISUSE_STOP
IGNORE_CONSTRUCTOR_SHADOW_FIELDS_STOP
IGNORE_WEAK_VTABLES_STOP
IGNORE_UNKNOWN_DOC_COMMAND_STOP
IGNORE_SIGNED_BITFIELD_STOP
IGNORE_PADDING_STOP
