set(CMAKE_SYSTEM_VERSION "10.0.16299.0")

set(CMAKE_C_FLAGS_DEBUG "/Od /Zi")
set(CMAKE_CXX_FLAGS_DEBUG "/Od /Zi")

set(CMAKE_C_FLAGS_RELEASE "/Ox /Ob2 /Gw /Gy /GL")
SET(CMAKE_CXX_FLAGS_RELEASE "/Ox /Ob2 /Gw /Gy /GL")

SET(CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT "${CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT} /LTCG")
SET(CMAKE_SHARED_LINKER_FLAGS_INIT "${CMAKE_SHARED_LINKER_FLAGS_RELEASE_INIT} /LTCG")
SET(CMAKE_STATIC_LINKER_FLAGS_INIT "${CMAKE_STATIC_LINKER_FLAGS_RELEASE_INIT} /LTCG")
#SET(CMAKE_MODULE_LINKER_FLAGS_RELEASE_INIT "${CMAKE_MODULE_LINKER_FLAGS_RELEASE_INIT /LTCG")
