#include <Hyperion/HyperionDef.h>

IGNORE_UNUSED_MACROS_START

#define DOCTEST_CONFIG_NO_SHORT_MACRO_NAMES
#define DOCTEST_CONFIG_NO_COMPARISON_WARNING_SUPPRESSION
#define DOCTEST_CONFIG_USE_STD_HEADERS
#define DOCTEST_CONFIG_SUPER_FAST_ASSERTS
#define DOCTEST_CONFIGURE_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

IGNORE_UNUSED_MACROS_STOP

#include <Hyperion/Utils.h>
